"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# import os
from setuptools import setup
import requests.certs
# from itertools import chain
# paths = ('eos/db/migrations', 'service/conversions')
# for root, folders, files in chain.from_iterable(os.walk(path) for path in paths):
#     for file_ in files:
#         if file_.endswith(".py") and not file_.startswith("_"):
#             mod_name = "{}.{}".format(
#                 root.replace("/", "."),
#                 file_.split(".py")[0],
#             )
#             print(mod_name)
APP = ['pyfa.py']
DATA_FILES = [
    ('imgs', ['imgs/gui','imgs/icons','imgs/renders']),
    ('service/jargon', ['service/jargon/header.yaml',"service/jargon/defaults.yaml"]),
    ('.',['README.md','eve.db',requests.certs.where(),'LICENSE','version.yml','dist_assets/win/pyfa.ico'])
]
OPTIONS = {
    'iconfile': 'dist_assets/mac/pyfa.icns',
    'packages': [
         'wx',
         'logbook',
         'dateutil',
        'requests',
         'sqlalchemy',
         'cryptography',
         'markdown2',
         'packaging',
         'bs4',
         'roman',
          'yaml'
    ],
    'excludes':['Tkinter'],
    'plist' : {
        'NSHighResolutionCapable': 'True',
        'NSPrincipalClass': 'NSApplication',
        'CFBundleName': 'pyfa',
        'CFBundleDisplayName': 'pyfa',
        'CFBundleIdentifier': 'org.pyfaorg.pyfa',
        'CFBundleVersion': '1.2.3',
        'CFBundleShortVersionString': '1.2.3',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
